import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import '../widgets/custom_info.dart';

class NotificationScreen extends StatefulWidget {
  const NotificationScreen({super.key});

  @override
  State<NotificationScreen> createState() => _NotificationScreenState();
}

class _NotificationScreenState extends State<NotificationScreen> {
  // General Enhancement: 15 Notifications with Post Details
  final List<Map<String, dynamic>> _notifications = [
    {
      'name': 'Cyrus Robles',
      'post': 'liked your post',
      'description': '5 minutes ago',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
    {
      'name': 'Maria Santos',
      'post': 'commented on your post',
      'description': '"Great content!" • 15 minutes ago',
      'commentText': 'Great content!',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
    {
      'name': 'John Dela Cruz',
      'post': 'shared your post',
      'description': '32 minutes ago',
      'postContent': 'First day sa gym, nabawasan ako ng 80 pesos!',
      'postDate': '1 day ago',
      'postLikes': 32,
      'postComments': 8,
      'postShares': 2,
      'hasImage': false,
      'imageUrl': '',
    },
    {
      'name': 'Anna Garcia',
      'post': 'started following you',
      'description': '1 hour ago',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
    {
      'name': 'Luis Fernandez',
      'post': 'liked your post',
      'description': '2 hours ago',
      'postContent': 'First day sa gym, nabawasan ako ng 80 pesos!',
      'postDate': '1 day ago',
      'postLikes': 32,
      'postComments': 8,
      'postShares': 2,
      'hasImage': false,
      'imageUrl': '',
    },
    {
      'name': 'Sofia Martinez',
      'post': 'commented on your post',
      'description': '"Amazing!" • 3 hours ago',
      'commentText': 'Amazing!',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
    {
      'name': 'Pedro Gonzales',
      'post': 'liked your comment',
      'description': '4 hours ago',
      'commentText': 'Your comment',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
    {
      'name': 'Elena Rodrigues',
      'post': 'shared your post',
      'description': '5 hours ago',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
    {
      'name': 'Carlos Mendoza',
      'post': 'started following you',
      'description': '6 hours ago',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
    {
      'name': 'Rosa Flores',
      'post': 'liked your post',
      'description': '1 day ago',
      'postContent': 'First day sa gym, nabawasan ako ng 80 pesos!',
      'postDate': '1 day ago',
      'postLikes': 32,
      'postComments': 8,
      'postShares': 2,
      'hasImage': false,
      'imageUrl': '',
    },
    {
      'name': 'Miguel Torres',
      'post': 'mentioned you in a comment',
      'description': '1 day ago',
      'commentText': 'Hey, check this out!',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
    {
      'name': 'Isabella Cruz',
      'post': 'reacted to your story',
      'description': '2 days ago',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
    {
      'name': 'Gabriel Lim',
      'post': 'sent you a friend request',
      'description': '3 days ago',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
    {
      'name': 'Jasmine Lee',
      'post': 'invited you to join a group',
      'description': '4 days ago',
      'postContent': 'First day sa gym, nabawasan ako ng 80 pesos!',
      'postDate': '1 day ago',
      'postLikes': 32,
      'postComments': 8,
      'postShares': 2,
      'hasImage': false,
      'imageUrl': '',
    },
    {
      'name': 'Rafael Santos',
      'post': 'liked your cover photo',
      'description': '1 week ago',
      'postContent': 'We cute',
      'postDate': '2 hours ago',
      'postLikes': 45,
      'postComments': 12,
      'postShares': 3,
      'hasImage': true,
      'imageUrl': 'assets/images/bebi.jpg',
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.white,
        width: 1.sw,
        child: ListView.separated(
          itemCount: _notifications.length,
          separatorBuilder: (context, index) => const Divider(),
          itemBuilder: (context, index) {
            final item = _notifications[index];
            return CustomInformation(
              name: item['name']!,
              post: item['post']!,
              description: item['description']!,
              date: '',
              numOfLikes: 0,
              postContent: item['postContent'] ?? '',
              postDate: item['postDate'] ?? '',
              postLikes: item['postLikes'] ?? 0,
              postComments: item['postComments'] ?? 0,
              postShares: item['postShares'] ?? 0,
              imageUrl: item['imageUrl'] ?? '',
              hasImage: item['hasImage'] ?? false,
              userName: 'Ivan Ezekiel Regodon',
              commentText: item['commentText'] ?? '',
            );
          },
        ),
      ),
    );
  }
}
